// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hillarys_Hair_Care.Migrations
{
    [DbContext(typeof(HillarysHairCareDbContext))]
    partial class HillarysHairCareDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HillarysHairCare.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("StylistId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StylistId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 6,
                            StartTime = new DateTime(2024, 2, 14, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 4,
                            StartTime = new DateTime(2024, 6, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 3
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 5,
                            StartTime = new DateTime(2024, 11, 30, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 6
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 2,
                            StartTime = new DateTime(2025, 1, 12, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        });
                });

            modelBuilder.Entity("HillarysHairCare.Models.AppointmentService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ServiceId");

                    b.ToTable("AppointmentServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 1,
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 3,
                            AppointmentId = 2,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 4,
                            AppointmentId = 2,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 5,
                            AppointmentId = 3,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 6,
                            AppointmentId = 4,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 7,
                            AppointmentId = 4,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 8,
                            AppointmentId = 4,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 9,
                            AppointmentId = 4,
                            ServiceId = 5
                        });
                });

            modelBuilder.Entity("HillarysHairCare.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "StamosJohn@Email.com",
                            FirstName = "John",
                            LastName = "Stamos",
                            PhoneNumber = "816-555-1234"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Mark@Denmark.Gov",
                            FirstName = "Mark",
                            LastName = "Denmark",
                            PhoneNumber = "153-555-9876"
                        },
                        new
                        {
                            Id = 3,
                            Email = "ssarahM@Example.co",
                            FirstName = "Sarah",
                            LastName = "Mcgill",
                            PhoneNumber = "555-533-5343"
                        },
                        new
                        {
                            Id = 4,
                            Email = "TrissTheSorceress@Novigrad.place",
                            FirstName = "Triss",
                            LastName = "Merrigold",
                            PhoneNumber = "456-123-9559"
                        },
                        new
                        {
                            Id = 5,
                            Email = "CmdrShepN7@Normandy.spc",
                            FirstName = "John",
                            LastName = "Shephard",
                            PhoneNumber = "555-555-5555"
                        },
                        new
                        {
                            Id = 6,
                            Email = "PanPam@NC.nom",
                            FirstName = "Panam",
                            LastName = "Palmer",
                            PhoneNumber = "818-555-2332"
                        });
                });

            modelBuilder.Entity("HillarysHairCare.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hair Cut",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Color",
                            Price = 19.50m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Beard Trim",
                            Price = 10.00m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sparkle",
                            Price = 40.99m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Compliment",
                            Price = 99.99m
                        });
                });

            modelBuilder.Entity("HillarysHairCare.Models.Stylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stylists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Joey@cutitout.sf",
                            FirstName = "Dave",
                            IsActive = true,
                            LastName = "Coulier",
                            PhoneNumber = "565-565-5656"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Wolfguy@Witcher.mon",
                            FirstName = "Geralt",
                            IsActive = true,
                            LastName = "Rivia",
                            PhoneNumber = "919-191-5555"
                        },
                        new
                        {
                            Id = 3,
                            Email = "GVak@C-Sec.hq",
                            FirstName = "Garrus",
                            IsActive = true,
                            LastName = "Vakarrian",
                            PhoneNumber = "655-555-5556"
                        },
                        new
                        {
                            Id = 4,
                            Email = "swiss@land.choc",
                            FirstName = "Swiss",
                            IsActive = false,
                            LastName = "Switzel",
                            PhoneNumber = "111-555-1155"
                        },
                        new
                        {
                            Id = 5,
                            Email = "JudeMoxx@BD.V",
                            FirstName = "Judy",
                            IsActive = false,
                            LastName = "Alvarez",
                            PhoneNumber = "222-555-5522"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Gale@Waterdeep.wiz",
                            FirstName = "Gale",
                            IsActive = true,
                            LastName = "Waterdeep",
                            PhoneNumber = "755-667-7776"
                        });
                });

            modelBuilder.Entity("HillarysHairCare.Models.Appointment", b =>
                {
                    b.HasOne("HillarysHairCare.Models.Customer", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HillarysHairCare.Models.Stylist", "Stylist")
                        .WithMany("Appointments")
                        .HasForeignKey("StylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Stylist");
                });

            modelBuilder.Entity("HillarysHairCare.Models.AppointmentService", b =>
                {
                    b.HasOne("HillarysHairCare.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HillarysHairCare.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HillarysHairCare.Models.Customer", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("HillarysHairCare.Models.Stylist", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
